Update update-dumps.yml

diff --git a/.github/workflows/update-dumps.yml b/.github/workflows/update-dumps.yml
--- a/.github/workflows/update-dumps.yml
+++ b/.github/workflows/update-dumps.yml
@@ -27,17 +27,22 @@ jobs:
           ref: 'main'
           path: ./runelite
 
-      - name: Set up JDK 21
+      - name: Set up JDK 11
         uses: actions/setup-java@v5
         with:
           distribution: temurin
-          java-version: 21
-          cache: gradle
+          java-version: 11
+
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v5
+        with:
+          gradle-version: wrapper
 
       - name: Build RuneLite (cache)
         run: |
           cd runelite
           ./gradlew --build-cache :cache:fatJar -x test -x javadoc -q
+          ls cache/build/libs
       - name: Build RuneLite (client)
         run: |
           cd runelite
@@ -45,8 +50,8 @@ jobs:
       - name: Copy to staging
         run: |
           mkdir -p staging
-          find runelite -name "cache-*-SNAPSHOT.jar" -exec cp {} staging/cache.jar \;
-          find runelite -name "client-*-SNAPSHOT-shaded.jar" -exec cp {} staging/client.jar \;
+          find runelite -name "cache-*-SNAPSHOT.jar" -exec cp {} staging/ \;
+          find runelite -name "client-*-SNAPSHOT-shaded.jar" -exec cp {} staging/ \;
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
         with:
@@ -86,7 +91,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -99,8 +104,8 @@ jobs:
           Copy-Item -Recurse -Force "tools/preferences/*.dat" $runeliteCacheDir
       - name: Run RuneLite (java)
         run: |
-          $jar = Get-ChildItem runelite-jars -Filter "client.jar" | Select-Object -First 1
-          if (-not $jar) { Write-Error "Client jar not found"; exit 1 }
+          $jar = Get-ChildItem runelite-jars -Filter "*-shaded.jar" | Select-Object -First 1
+          if (-not $jar) { Write-Error "Shaded jar not found"; exit 1 }
           $process = Start-Process -FilePath "java" -ArgumentList "-Dfile.encoding=UTF8 -jar", $jar.FullName -NoNewWindow -PassThru -RedirectStandardOutput "output.log" -RedirectStandardError "error.log"
           while (-not $process.HasExited) {
             if (Test-Path "output.log") {
@@ -142,7 +147,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -156,9 +161,8 @@ jobs:
       - name: Run SimbaItemDumper (java)
         run: |
           mkdir -p cache/output
-          tree -L 2
-          java -cp staging/cache.jar "net.runelite.cache.SimbaItemDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaItemDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
           cd cache/output/${{ inputs.cache_version }}/items
           zip -r items.zip ./*.json
       - name: Upload Items
@@ -175,7 +179,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -189,8 +193,8 @@ jobs:
       - name: Run SimbaItemDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaGearDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaGearDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Upload Items
         uses: actions/upload-artifact@v4
         with:
@@ -205,7 +209,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -219,8 +223,8 @@ jobs:
       - name: Run SimbaCollisionMapDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaCollisionMapDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaCollisionMapDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Upload Collision Maps
         uses: actions/upload-artifact@v4
         with:
@@ -235,7 +239,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -249,8 +253,8 @@ jobs:
       - name: Run SimbaHeightMapDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaHeightMapDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaHeightMapDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Upload Height Maps
         uses: actions/upload-artifact@v4
         with:
@@ -265,7 +269,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -279,8 +283,8 @@ jobs:
       - name: Run SimbaMapImageDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaMapImageDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaMapImageDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Upload Map Images
         uses: actions/upload-artifact@v4
         with:
@@ -295,7 +299,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -309,8 +313,8 @@ jobs:
       - name: Run SimbaMapImageDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaMapImageDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output" -noicons
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaMapImageDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output -noicons
       - name: Upload Map Images
         uses: actions/upload-artifact@v4
         with:
@@ -325,7 +329,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -339,8 +343,8 @@ jobs:
       - name: Run SimbaNPCDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaNPCDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaNPCDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Zip NPCs folder
         run: |
             cd cache/output/${{ inputs.cache_version }}/NPCs
@@ -359,7 +363,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -373,8 +377,8 @@ jobs:
       - name: Run SimbaObjectInfoDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaObjectInfoDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaObjectInfoDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Upload Object Info
         uses: actions/upload-artifact@v4
         with:
@@ -389,7 +393,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -403,8 +407,8 @@ jobs:
       - name: Run Simba1400ObjectInfoDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.Simba1400ObjectInfoDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.Simba1400ObjectInfoDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Upload Object Info
         uses: actions/upload-artifact@v4
         with:
@@ -419,7 +423,7 @@ jobs:
         uses: actions/setup-java@v5
         with:
           distribution: 'temurin'
-          java-version: 21
+          java-version: '11'
       - name: Download RuneLite artifacts
         uses: actions/download-artifact@v4
         with:
@@ -433,8 +437,8 @@ jobs:
       - name: Run SimbaSpriteDumper (java)
         run: |
           mkdir -p cache/output
-          java -cp staging/cache.jar "net.runelite.cache.SimbaSpriteDumper" \
-            --cachedir "cache/input" --cachename "${{ inputs.cache_version }}" --outputdir "cache/output"
+          java -cp staging/cache-*-SNAPSHOT.jar net.runelite.cache.SimbaSpriteDumper \
+            --cachedir cache/input --cachename ${{ inputs.cache_version }} --outputdir cache/output
       - name: Zip sprites folder
         run: |
             cd cache/output/${{ inputs.cache_version }}/Sprites
